version: 0.2

env:
  variables:
    REGION: us-east-1
    REPOSITORY_URL: 664418951912.dkr.ecr.us-east-1.amazonaws.com/backend-nodejs
    DOCKER_CONTAINER_NAME: nodejs-project-ecr-container

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 664418951912.dkr.ecr.us-east-1.amazonaws.com || { echo "Docker login failed"; exit 1; }
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Checking Dockerfile...
      - ls -la
      - cat Dockerfile
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - echo Writing image definitions file...

      #Give your container name
      - DOCKER_CONTAINER_NAME=nodejs-demo-ecr-container
      - printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_CONTAINER_NAME" "$REPOSITORY_URL:$IMAGE_TAG" > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/nodejs-project-aws-deploy.jar
